//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все известные форматы (*.adr;*.from;*.xml)|*.adr;*.from;*.xml|Файл адресации данных FRom(*.from)|*.from|Файл адресации данных XML(*.xml)|*.xml|Файл RomEdit или Nistune(*.adr)|*.adr.
        /// </summary>
        internal static string adrFilesToShowOpen {
            get {
                return ResourceManager.GetString("adrFilesToShowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл адресации данных XML(*.xml)|*.xml|Файл адресации данных FRom(*.from)|*.from.
        /// </summary>
        internal static string adrFilesToShowSave {
            get {
                return ResourceManager.GetString("adrFilesToShowSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все известные файлы (*.adr;*.bin;*.from;*.xml)|*.adr;*.bin;*.from;*.xml|Файл адресации данных XML(*.xml)|*.xml|Файл адресации данных FRom(*.from)|*.from|Файл RomEdit или Nistune(*.adr)|*.adr.
        /// </summary>
        internal static string AllKnownFiles {
            get {
                return ResourceManager.GetString("AllKnownFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки (*.bin)|*.bin|Все файлы (*.*)|*.*.
        /// </summary>
        internal static string binFilesToShowOpen {
            get {
                return ResourceManager.GetString("binFilesToShowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки (*.bin)|*.bin|Все файлы (*.*)|*.*.
        /// </summary>
        internal static string binFilesToShowSave {
            get {
                return ResourceManager.GetString("binFilesToShowSave", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Button_Add_01 {
            get {
                object obj = ResourceManager.GetObject("Button_Add_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Button_Blank_Green_01 {
            get {
                object obj = ResourceManager.GetObject("Button_Blank_Green_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Button_Blank_Red_01 {
            get {
                object obj = ResourceManager.GetObject("Button_Blank_Red_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Button_Delete_01 {
            get {
                object obj = ResourceManager.GetObject("Button_Delete_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный тип файлов не поддерживается! Выбран файл: &apos;{0}&apos;.
        /// </summary>
        internal static string exMsgNotSupportedFileFormat {
            get {
                return ResourceManager.GetString("exMsgNotSupportedFileFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap File_New_01 {
            get {
                object obj = ResourceManager.GetObject("File_New_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgConnected_16x16 {
            get {
                object obj = ResourceManager.GetObject("imgConnected_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgConnecting_16x16 {
            get {
                object obj = ResourceManager.GetObject("imgConnecting_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDisconnected_16x16 {
            get {
                object obj = ResourceManager.GetObject("imgDisconnected_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSettings_16x16 {
            get {
                object obj = ResourceManager.GetObject("imgSettings_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
