//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection cfg_RecentBinFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cfg_RecentBinFiles"]));
            }
            set {
                this["cfg_RecentBinFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection cfg_RecentAdrFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cfg_RecentAdrFiles"]));
            }
            set {
                this["cfg_RecentAdrFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_OpenLastConfig {
            get {
                return ((bool)(this["cfg_OpenLastConfig"]));
            }
            set {
                this["cfg_OpenLastConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfg_dlgADRPath {
            get {
                return ((string)(this["cfg_dlgADRPath"]));
            }
            set {
                this["cfg_dlgADRPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfg_dlgROMPath {
            get {
                return ((string)(this["cfg_dlgROMPath"]));
            }
            set {
                this["cfg_dlgROMPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adr\\")]
        public string cfg_ADRFilesPath {
            get {
                return ((string)(this["cfg_ADRFilesPath"]));
            }
            set {
                this["cfg_ADRFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin\\")]
        public string cfg_ROMFilesPath {
            get {
                return ((string)(this["cfg_ROMFilesPath"]));
            }
            set {
                this["cfg_ROMFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM11")]
        public string cfg_ConsultPort {
            get {
                return ((string)(this["cfg_ConsultPort"]));
            }
            set {
                this["cfg_ConsultPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfg_EmulatorPort {
            get {
                return ((string)(this["cfg_EmulatorPort"]));
            }
            set {
                this["cfg_EmulatorPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfg_ConsultConnectAtStartup {
            get {
                return ((bool)(this["cfg_ConsultConnectAtStartup"]));
            }
            set {
                this["cfg_ConsultConnectAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfg_EmulatorConnectAtStartup {
            get {
                return ((bool)(this["cfg_EmulatorConnectAtStartup"]));
            }
            set {
                this["cfg_EmulatorConnectAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_EmulatorSaveFileAfterRead {
            get {
                return ((bool)(this["cfg_EmulatorSaveFileAfterRead"]));
            }
            set {
                this["cfg_EmulatorSaveFileAfterRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public char cfg_ConsultDiagECUType {
            get {
                return ((char)(this["cfg_ConsultDiagECUType"]));
            }
            set {
                this["cfg_ConsultDiagECUType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfg_UserName {
            get {
                return ((string)(this["cfg_UserName"]));
            }
            set {
                this["cfg_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfg_UserEmail {
            get {
                return ((string)(this["cfg_UserEmail"]));
            }
            set {
                this["cfg_UserEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_ConsultKeepALive {
            get {
                return ((bool)(this["cfg_ConsultKeepALive"]));
            }
            set {
                this["cfg_ConsultKeepALive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_FormLogTopMost {
            get {
                return ((bool)(this["cfg_FormLogTopMost"]));
            }
            set {
                this["cfg_FormLogTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_FormLogAttachToMain {
            get {
                return ((bool)(this["cfg_FormLogAttachToMain"]));
            }
            set {
                this["cfg_FormLogAttachToMain"] = value;
            }
        }
    }
}
