//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap pngAccept {
            get {
                object obj = ResourceManager.GetObject("pngAccept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngAdd {
            get {
                object obj = ResourceManager.GetObject("pngAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngDatabase_save {
            get {
                object obj = ResourceManager.GetObject("pngDatabase_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngDelete {
            get {
                object obj = ResourceManager.GetObject("pngDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngEmulatorStreamMode {
            get {
                object obj = ResourceManager.GetObject("pngEmulatorStreamMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngExclamation {
            get {
                object obj = ResourceManager.GetObject("pngExclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngGraphShowSwitch {
            get {
                object obj = ResourceManager.GetObject("pngGraphShowSwitch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngOpenADR {
            get {
                object obj = ResourceManager.GetObject("pngOpenADR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngOpenBIN {
            get {
                object obj = ResourceManager.GetObject("pngOpenBIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngPage_white_add {
            get {
                object obj = ResourceManager.GetObject("pngPage_white_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngSaveBIN {
            get {
                object obj = ResourceManager.GetObject("pngSaveBIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngStop {
            get {
                object obj = ResourceManager.GetObject("pngStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngTable_save {
            get {
                object obj = ResourceManager.GetObject("pngTable_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pngToggleProp {
            get {
                object obj = ResourceManager.GetObject("pngToggleProp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все известные форматы (*.adr;*.from;*.xml)|*.adr;*.from;*.xml|Файл адресации данных FRom(*.from)|*.from|Файл адресации данных XML(*.xml)|*.xml|Файл RomEdit или Nistune(*.adr)|*.adr.
        /// </summary>
        public static string strAdrFilesToShowOpen {
            get {
                return ResourceManager.GetString("strAdrFilesToShowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл адресации данных XML(*.xml)|*.xml|Файл адресации данных FRom(*.from)|*.from.
        /// </summary>
        public static string strAdrFilesToShowSave {
            get {
                return ResourceManager.GetString("strAdrFilesToShowSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все известные файлы (*.adr;*.bin;*.from;*.xml)|*.adr;*.bin;*.from;*.xml|Файл адресации данных XML(*.xml)|*.xml|Файл адресации данных FRom(*.from)|*.from|Файл RomEdit или Nistune(*.adr)|*.adr.
        /// </summary>
        public static string strAllKnownFiles {
            get {
                return ResourceManager.GetString("strAllKnownFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки (*.bin)|*.bin|Все файлы (*.*)|*.*.
        /// </summary>
        public static string strBinFilesToShowOpen {
            get {
                return ResourceManager.GetString("strBinFilesToShowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки (*.bin)|*.bin|Все файлы (*.*)|*.*.
        /// </summary>
        public static string strBinFilesToShowSave {
            get {
                return ResourceManager.GetString("strBinFilesToShowSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный тип файлов не поддерживается! Выбран файл: &apos;{0}&apos;.
        /// </summary>
        public static string strExMsgNotSupportedFileFormat {
            get {
                return ResourceManager.GetString("strExMsgNotSupportedFileFormat", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap tyre_params {
            get {
                object obj = ResourceManager.GetObject("tyre_params", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
